"""update table utilisateur

Revision ID: 019c3b48cf60
Revises: 48cfbd909fd7
Create Date: 2025-09-12 10:18:00.196118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019c3b48cf60'
down_revision: Union[str, Sequence[str], None] = '48cfbd909fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('date_de_naissance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'date_de_naissance')
    # ### end Alembic commands ###
