"""Création des tables initiales

Revision ID: 0ba85d51a4e7
Revises: 
Create Date: 2025-09-04 16:30:44.992714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba85d51a4e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('nom_de_famille', sa.String(), nullable=False),
    sa.Column('date_de_naissance', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
