"""delete FK commentaire for livre

Revision ID: 37ee6b127ea4
Revises: 8cec05dd19a7
Create Date: 2025-09-11 14:40:23.624346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ee6b127ea4'
down_revision: Union[str, Sequence[str], None] = '8cec05dd19a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
