"""delete user from role table

Revision ID: 48cfbd909fd7
Revises: a92f24b86018
Create Date: 2025-09-11 15:16:08.654892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cfbd909fd7'
down_revision: Union[str, Sequence[str], None] = 'a92f24b86018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('comportement', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotions', 'comportement')
    # ### end Alembic commands ###
