"""update nullable value for  table utilisateur

Revision ID: 4ca62d5c1c44
Revises: 019c3b48cf60
Create Date: 2025-09-12 10:19:11.364406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca62d5c1c44'
down_revision: Union[str, Sequence[str], None] = '019c3b48cf60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'nom_de_famille',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'nom_de_famille',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('utilisateurs', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
