"""add date_modification for all table

Revision ID: 736e1fda70cd
Revises: e44d7168c0d3
Create Date: 2025-09-11 10:09:40.680720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736e1fda70cd'
down_revision: Union[str, Sequence[str], None] = 'e44d7168c0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapitres', sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('editeurs', sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('emotions', sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('livres', sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('personas', sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('utilisateurs', sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'date_modification')
    op.drop_column('roles', 'date_modification')
    op.drop_column('personas', 'date_modification')
    op.drop_column('livres', 'date_modification')
    op.drop_column('emotions', 'date_modification')
    op.drop_column('editeurs', 'date_modification')
    op.drop_column('chapitres', 'date_modification')
    # ### end Alembic commands ###
