"""Create all core tables

Revision ID: fa91638d9cfe
Revises: 23c299b8e84e
Create Date: 2025-09-11 09:31:49.049698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa91638d9cfe'
down_revision: Union[str, Sequence[str], None] = '23c299b8e84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('editeurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('emotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('livres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('contenu_pour_majeur', sa.Boolean(), nullable=False),
    sa.Column('date_de_publication', sa.DateTime(), nullable=True),
    sa.Column('date_d_ajout', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('auteur_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapitres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('numero_chapitre', sa.Integer(), nullable=False),
    sa.Column('livre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('auteur_id', sa.UUID(), nullable=False),
    sa.Column('livre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livres_genres_association',
    sa.Column('livre_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ),
    sa.PrimaryKeyConstraint('livre_id', 'genre_id')
    )
    op.add_column('utilisateurs', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('utilisateurs', sa.Column('date_de_creation_du_compte', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('utilisateurs', sa.Column('cgu', sa.Boolean(), nullable=False))
    op.add_column('utilisateurs', sa.Column('rgpd', sa.Boolean(), nullable=False))
    op.add_column('utilisateurs', sa.Column('cookies', sa.Boolean(), nullable=False))
    op.add_column('utilisateurs', sa.Column('auteur_prefere_id', sa.UUID(), nullable=True))
    op.add_column('utilisateurs', sa.Column('chatbot_prefere_id', sa.UUID(), nullable=True))
    op.add_column('utilisateurs', sa.Column('role_id', sa.UUID(), nullable=False))
    op.alter_column('utilisateurs', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('utilisateurs', 'nom_de_famille',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'utilisateurs', 'utilisateurs', ['auteur_prefere_id'], ['id'])
    op.create_foreign_key(None, 'utilisateurs', 'chatbots', ['chatbot_prefere_id'], ['id'])
    op.create_foreign_key(None, 'utilisateurs', 'roles', ['role_id'], ['id'])
    op.drop_column('utilisateurs', 'date_de_naissance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('date_de_naissance', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'utilisateurs', type_='foreignkey')
    op.drop_constraint(None, 'utilisateurs', type_='foreignkey')
    op.drop_constraint(None, 'utilisateurs', type_='foreignkey')
    op.alter_column('utilisateurs', 'nom_de_famille',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'prenom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('utilisateurs', 'role_id')
    op.drop_column('utilisateurs', 'chatbot_prefere_id')
    op.drop_column('utilisateurs', 'auteur_prefere_id')
    op.drop_column('utilisateurs', 'cookies')
    op.drop_column('utilisateurs', 'rgpd')
    op.drop_column('utilisateurs', 'cgu')
    op.drop_column('utilisateurs', 'date_de_creation_du_compte')
    op.drop_column('utilisateurs', 'avatar')
    op.drop_table('livres_genres_association')
    op.drop_table('commentaires')
    op.drop_table('chapitres')
    op.drop_table('livres')
    op.drop_table('roles')
    op.drop_table('personas')
    op.drop_table('genres')
    op.drop_table('emotions')
    op.drop_table('editeurs')
    op.drop_table('chatbots')
    # ### end Alembic commands ###
