# Nom du workflow, visible dans l'onglet "Actions" de GitHub
name: Validation Continue (CI)

# Déclencheurs
on:
  push:
    branches: [ "main", "develop" ] # Ou les noms de vos branches principales
  pull_request:
    branches: [ "main" ]

# Tâches à exécuter
jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Mettre en place Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Lancer les tests avec couverture
      - name: Run tests with coverage
        run: pytest --cov=src